version: "3"

services:
  minio:
#    image: minio/minio:RELEASE.2023-07-11T21-29-34Z
    image: minio/minio:RELEASE.2024-01-29T03-56-32Z
    restart: always
#    user: "10001"
    ports:
      - 19000:9000
      - 19001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: s3cr3tk3y
#      TZ: EET
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
    driver: local
